source 'https://rubygems.org'

ruby '3.3.0'

gem 'activerecord'
gem 'activesupport'
gem 'amazing_print'
gem 'bundler'
gem 'csv'
gem 'dotenv'
gem 'database_cleaner'
gem 'enumerize'
gem "httparty"
gem 'oj'
gem 'parallel_tests'
gem 'pg'
gem 'pry', require: false
gem 'pry-byebug', require: false
gem 'rack'
gem 'rake'
gem 'rb-readline'
gem 'rspec'
gem 'rubocop'
gem 'sinatra'
gem 'sinatra-activerecord'
gem 'standalone_migrations'
gem 'tzinfo'